# **[필수과제2] 유사도 (전처리 비교)**
- 아무것도 하지않고 진행한 것과 전처리 후 진행한 것 비교
- 불용어 처리, 기타 전처리 진행하기

---



In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('movie_rv.csv')

In [5]:
df['document'] = df['document'].fillna(0)
df['document'] = df['document'].astype(str)

In [6]:
# 공백 제거
df['new_doc'] = df['document'].str.strip().astype(str)

In [7]:
# 특수문자 제거
df['new_doc'] = df['document'].str.replace(r'[^\uAC00-\uD7A30-9a-zA-Z\s]', '')

<ipython-input-7-0ac35923674f>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df['new_doc'] = df['document'].str.replace(r'[^\uAC00-\uD7A30-9a-zA-Z\s]', '')


In [8]:
df

Unnamed: 0        id  \
0                0   9976970   
1                1   3819312   
2                2  10265843   
3                3   9045019   
4                4   6483659   
...            ...       ...   
149995      149995   6222902   
149996      149996   8549745   
149997      149997   9311800   
149998      149998   2376369   
149999      149999   9619869   

                                                 document  label  \
0                                     아 더빙.. 진짜 짜증나네요 목소리      0   
1                       흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1   
2                                       너무재밓었다그래서보는것을추천한다      0   
3                           교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0   
4       사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1   
...                                                   ...    ...   
149995                                인간이 문제지.. 소는 뭔죄인가..      0   
149996                                      평점이 너무 낮아서...      1   
149997                    이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?      0   
149998                        청춘 영화의 최고봉.방황과 우울했던 날들의 자화상      1   
149999                           한국 영화 최초로 수간하는 내용이 담긴 영화      0   

                                                  new_doc  
0                                       아 더빙 진짜 짜증나네요 목소리  
1                              흠포스터보고 초딩영화줄오버연기조차 가볍지 않구나  
2                                       너무재밓었다그래서보는것을추천한다  
3                               교도소 이야기구먼 솔직히 재미는 없다평점 조정  
4       사이몬페그의 익살스런 연기가 돋보였던 영화스파이더맨에서 늙어보이기만 했던 커스틴 던...  
...                                                   ...  
149995                                    인간이 문제지 소는 뭔죄인가  
149996                                         평점이 너무 낮아서  
149997                      이게 뭐요 한국인은 거들먹거리고 필리핀 혼혈은 착하다  
149998                         청춘 영화의 최고봉방황과 우울했던 날들의 자화상  
149999                           한국 영화 최초로 수간하는 내용이 담긴 영화  

[150000 rows x 5 columns]

# 1. 전처리 전

---



## 1) CountVectorizer

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
re_cv = CountVectorizer(max_features=1000)

In [11]:
re_dtm = re_cv.fit_transform(df['document'])

In [12]:
re_dtm

<150000x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 369291 stored elements in Compressed Sparse Row format>

In [13]:
re_cv.get_feature_names_out()[:100]

array(['0점', '0점은', '10', '10점', '1점', '1점도', '2점', '3류', '3점', '4점',
       '80년대', '90년대', '9점', 'b급', 'good', 'oo', 'ooo', 'ooo기', 'ost',
       'the', 'tv', 'ㄷㄷ', 'ㅅㅂ', 'ㅇㅇ', 'ㅉㅉ', 'ㅋㅋ', 'ㅋㅋㅋ', 'ㅋㅋㅋㅋ', 'ㅋㅋㅋㅋㅋ',
       'ㅎㅎ', 'ㅎㅎㅎ', 'ㅜㅜ', 'ㅠㅠ', 'ㅠㅠㅠ', 'ㅡㅡ', '가끔', '가는', '가볍게', '가서',
       '가슴', '가슴이', '가장', '가족', '가지고', '가진', '각본', '간만에', '갈수록', '감독',
       '감독님', '감독은', '감독의', '감독이', '감동', '감동과', '감동도', '감동을', '감동이',
       '감동적이고', '감동적인', '감사합니다', '감정을', '갑자기', '강추', '같네요', '같다', '같습니다',
       '같아', '같아서', '같아요', '같은', '같은데', '같음', '같이', '개연성', '개인적으로', '거의',
       '건지', '걸작', '겁나', '것도', '것은', '것을', '것이', '것이다', '게다가', '결국', '결말',
       '결말도', '결말은', '결말이', '계속', '공감', '공감이', '공포', '공포영화', '과연', '괜찮은',
       '괜히', '굉장히'], dtype=object)

In [14]:
pip install konlpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 65.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.6/488.6 kB 48.4 MB/s eta 0:00:00


In [15]:
from konlpy.tag import Okt

In [16]:
tw_tag = Okt()

In [17]:
def my_tokenizer(doc):
    return[
        token
        for token, pos in tw_tag.pos(doc)
        if pos in ['Noun','Verb']
    ]

In [18]:
print('결과', my_tokenizer(df.document[5]))

결과 ['막', '걸음', '마', '뗀', '세', '초등학교', '학년', '생인', '살용', '영화', '반개', '움']


In [19]:
re_cv = CountVectorizer(max_features=1000, tokenizer=my_tokenizer)

In [21]:
re_dtm = re_cv.fit_transform(df['document'])

In [23]:
for word, count in zip(re_cv.get_feature_names_out(), re_dtm[5].toarray()[0]):
    if count > 0:
        print(word, count, end=',')

마 1,막 1,반개 1,세 1,영화 1,움 1,

## 2) TF-IDF

In [24]:
from sklearn.feature_extraction.text import TfidfTransformer

In [25]:
transformer = TfidfTransformer()
transformer

TfidfTransformer()

In [26]:
rv_tfidf = transformer.fit_transform(re_dtm)

In [27]:
rv_tfidf

<150000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 676610 stored elements in Compressed Sparse Row format>

In [28]:
tf = TfidfTransformer()
rv_tfidf = tf.fit_transform(re_dtm)

## 3) Cosine_Similarity 유사도 확인

In [29]:
from sklearn.metrics.pairwise import cosine_similarity

In [30]:
st = len(df.document[5])//2

In [31]:
source = df.document[5][-st:]

In [32]:
df.document[5]

'막 걸음마 뗀 3세부터 초등학교 1학년생인 8살용영화.ㅋㅋㅋ...별반개도 아까움.'

In [33]:
st

22

In [34]:
source

' 8살용영화.ㅋㅋㅋ...별반개도 아까움.'

In [35]:
source_cv = re_cv.transform([source])

In [36]:
source_cv

<1x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [37]:
sim_res_cv = cosine_similarity(source_cv,re_dtm)

In [38]:
sim_res_cv

array([[0.        , 0.21821789, 0.        , ..., 0.        , 0.33333333,
        0.43643578]])

In [39]:
source_idf = tf.transform(source_cv)

In [40]:
source_idf

<1x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [41]:
sim_res_tfidf = cosine_similarity(source_idf, rv_tfidf)

In [42]:
sim_res_tfidf

array([[0.        , 0.0349782 , 0.        , ..., 0.        , 0.05028341,
        0.10674825]])

In [43]:
print('[CountVectorize] 가장 유사한 리뷰는?',np.argmax(sim_res_cv[0]))

[CountVectorize] 가장 유사한 리뷰는? 6728


In [44]:
print('[TF-IDF] 가장 유사한 리뷰는?',np.argmax(sim_res_tfidf[0]))

[TF-IDF] 가장 유사한 리뷰는? 11824


In [45]:
df.document[6728]

'영화 무서운게 아니고 징그러움.'

In [46]:
df.document[11824]

'반개도 아까움..67ㅕ465437'

## 3) 차이점 분석

In [71]:
# CountVectorizer 분석 결과
idx1 = list((-sim_res_cv[0]).argsort()[:10])
df.new_doc.loc[idx1]

114100               별반개도 아깝다 2000년대에 이런 영화가 만들어졌다는게 신기할 따름
67231                             깜찍함과 사랑스러움이 가득하고 행복해지는 영화
114376                              영화간에서 안보길 잘한듯 100원도 아까움
11824                                       반개도 아까움67465437
6728                                       영화 무서운게 아니고 징그러움
20267                                         억지스러움이 넘치는 영화
142164                             별반개도아까움 보다가 나왔음OOO 최악의영화
44052     별 반개도아까움 예전 하지원나온영화 가위랑 거이 비슷함 그영화에 억지로 분신사바하는...
5                     막 걸음마 뗀 3세부터 초등학교 1학년생인 8살용영화별반개도 아까움
15952                          별 반개도 아까움  아나 진짜 이런영화 왜만드는거야
Name: new_doc, dtype: object

In [72]:
# TF-IDF 분석 결과
idx2 = list((-sim_res_tfidf[0]).argsort()[:10])
df.new_doc.loc[idx2]

11824                            반개도 아까움67465437
142199                                 별 반개도 아까움
68154                            알바들드립쩌네별반개도 아까움
114100    별반개도 아깝다 2000년대에 이런 영화가 만들어졌다는게 신기할 따름
142164                  별반개도아까움 보다가 나왔음OOO 최악의영화
32037                              반개는 산의 아름다움이다
3859                                    별반개도 아깝다
4521                                      반개도아깝다
75879                                   반개도 아깝다 
82134                                   반개도 아깝다 
Name: new_doc, dtype: object

# 2. 전처리 후

---



## 1) CountVectorizer

In [47]:
df['new_doc']

0                                         아 더빙 진짜 짜증나네요 목소리
1                                흠포스터보고 초딩영화줄오버연기조차 가볍지 않구나
2                                         너무재밓었다그래서보는것을추천한다
3                                 교도소 이야기구먼 솔직히 재미는 없다평점 조정
4         사이몬페그의 익살스런 연기가 돋보였던 영화스파이더맨에서 늙어보이기만 했던 커스틴 던...
                                ...                        
149995                                      인간이 문제지 소는 뭔죄인가
149996                                           평점이 너무 낮아서
149997                        이게 뭐요 한국인은 거들먹거리고 필리핀 혼혈은 착하다
149998                           청춘 영화의 최고봉방황과 우울했던 날들의 자화상
149999                             한국 영화 최초로 수간하는 내용이 담긴 영화
Name: new_doc, Length: 150000, dtype: object

In [48]:
re_cv1 = CountVectorizer(max_features=1000)
re_cv1

CountVectorizer(max_features=1000)

In [49]:
re_dtm1 = re_cv1.fit_transform(df['new_doc'])
re_dtm1

<150000x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 344035 stored elements in Compressed Sparse Row format>

In [50]:
def my_tokenizer1(doc):
    return[
        token
        for token, pos in tw_tag.pos(doc)
        if pos in ['Noun', 'Verb']
    ]

In [51]:
print('결과', my_tokenizer1(df.new_doc[5]))

결과 ['막', '걸음', '마', '뗀', '세', '초등학교', '학년', '생인', '살용', '영화', '반개', '움']


In [52]:
re_cv1 = CountVectorizer(max_features=1000, tokenizer=my_tokenizer1)
re_cv1

CountVectorizer(max_features=1000,
                tokenizer=<function my_tokenizer1 at 0x7cd09bc32290>)

In [53]:
re_dtm1 = re_cv1.fit_transform(df['new_doc'])

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [54]:
for word, count in zip(re_cv1.get_feature_names_out(),
                       re_dtm1[5].toarray()[0]):
    if count > 0:
        print(word, count, end = ',')

마 1,막 1,반개 1,세 1,영화 1,움 1,

## 2) TF-IDF

In [55]:
transformer1 = TfidfTransformer()
transformer1

TfidfTransformer()

In [56]:
rv_tfidf1 = transformer1.fit_transform(re_dtm1)
rv_tfidf1

<150000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 671741 stored elements in Compressed Sparse Row format>

In [57]:
tf1 = TfidfTransformer()

In [58]:
re_tfidf1 = tf1.fit_transform(re_dtm1)
re_tfidf1

<150000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 671741 stored elements in Compressed Sparse Row format>

## 3) Cosine_Similarity 유사도 확인

In [59]:
st1 = len(df.new_doc[5])//2

In [60]:
source1 = df.new_doc[5][-st:]

In [61]:
st1

18

In [62]:
source1

'학교 1학년생인 8살용영화별반개도 아까움'

In [63]:
source_cv1 = re_cv1.transform([source1])
source_cv1

<1x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [64]:
sim_res1_cv = cosine_similarity(source_cv1, re_dtm1)
sim_res1_cv

array([[0.        , 0.18898224, 0.        , ..., 0.        , 0.28867513,
        0.37796447]])

In [65]:
source1_idf = tf.transform(source_cv1)
source1_idf

<1x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [66]:
sim_res1_tfidf = cosine_similarity(source1_idf, rv_tfidf)
sim_res1_tfidf

array([[0., 0., 0., ..., 0., 0., 0.]])

In [67]:
print('[CountVectorize] 가장 유사한 리뷰는?',np.argmax(sim_res1_cv[0]))

[CountVectorize] 가장 유사한 리뷰는? 6728


In [68]:
print('[TF-IDF] 가장 유사한 리뷰는?',np.argmax(sim_res1_tfidf[0]))

[TF-IDF] 가장 유사한 리뷰는? 61104


## 차이점 분석

In [69]:
# CountVectorizer 분석 결과
idx3 = list((-sim_res1_cv[0]).argsort()[:10])
df.new_doc.loc[idx3]

6728                                       영화 무서운게 아니고 징그러움
20267                                         억지스러움이 넘치는 영화
114376                              영화간에서 안보길 잘한듯 100원도 아까움
114100               별반개도 아깝다 2000년대에 이런 영화가 만들어졌다는게 신기할 따름
67231                             깜찍함과 사랑스러움이 가득하고 행복해지는 영화
33900                                       학교에서보던영화 재미있었어요
11824                                       반개도 아까움67465437
142164                             별반개도아까움 보다가 나왔음OOO 최악의영화
44052     별 반개도아까움 예전 하지원나온영화 가위랑 거이 비슷함 그영화에 억지로 분신사바하는...
475                      기대하지 않았던 영화의 아름다움이 밀려온다 꽤 괜찮다았던 영화
Name: new_doc, dtype: object

In [70]:
# TF-IDF 분석 결과
idx4 = list((-sim_res1_tfidf[0]).argsort()[:10])
df.new_doc.loc[idx4]

134968               인디언 출신 동료 병사와의 오글거리는 우정
133313              맨발의 투혼 그리고 무전기는 우정을 싣고  
126899                                    우정
64906                      너무 재밌다 세명의 우정도 깊고
61104                                  아픈 우정
107326                        벨과 세바스찬의 진한 우정
102202                     사운드에 놀라는 영화 모성애우정
93795                            우정에의한 우정의애니
5613      사랑과 우정이 묻어나는 영화최고 영화를 재미로만 판단하지맙시다
111746                               최고의우정이다
Name: new_doc, dtype: object