# **CountVectorize & TF-IDF**

---



In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('movie_rv.csv')

In [4]:
df.isna().sum()

Unnamed: 0    0
id            0
document      5
label         0
dtype: int64

In [5]:
df['document'] = df['document'].fillna(0)
df['document'] = df['document'].astype(str)

In [6]:
df_docu = df['document'].iloc[:50000]

In [7]:
df_docu

0                                      아 더빙.. 진짜 짜증나네요 목소리
1                        흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나
2                                        너무재밓었다그래서보는것을추천한다
3                            교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정
4        사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...
                               ...                        
49995    "이게 소위 스페인식 Neo-realism 이란 건가? - 물론, ""아동 판타지"...
49996                                     보지마셈 저 믿으세요 보지마셈
49997                                                 최고졸작
49998                                    재밌고 좋았음 10자 쓰라고?!
49999                                 소박하지만 잔잔한 감동을 주는 영화.
Name: document, Length: 50000, dtype: object

In [8]:
df_docu.isna().sum()

0

## CountVectorize
- bow 카운트 기반 (카운팅 하여 전처리 진행)

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
df['document']

0                                       아 더빙.. 진짜 짜증나네요 목소리
1                         흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나
2                                         너무재밓었다그래서보는것을추천한다
3                             교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정
4         사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...
                                ...                        
149995                                  인간이 문제지.. 소는 뭔죄인가..
149996                                        평점이 너무 낮아서...
149997                      이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?
149998                          청춘 영화의 최고봉.방황과 우울했던 날들의 자화상
149999                             한국 영화 최초로 수간하는 내용이 담긴 영화
Name: document, Length: 150000, dtype: object

max_features 빈도 기반, 우선순위 개수 제한

In [11]:
re_cv = CountVectorizer(max_features=1000)

In [12]:
re_dtm = re_cv.fit_transform(df_docu)

In [13]:
re_dtm

<50000x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 124124 stored elements in Compressed Sparse Row format>

In [14]:
re_cv.get_feature_names_out()[:100]

array(['0점', '0점은', '10', '10자', '10점', '1점', '1점도', '2점', '3류', '3점',
       '4점', '80년대', '90년대', '9점', 'b급', 'good', 'oo', 'ooo', 'ooo기',
       'ost', 'the', 'tv', 'ㄷㄷ', 'ㅅㅂ', 'ㅇㅇ', 'ㅉㅉ', 'ㅋㅋ', 'ㅋㅋㅋ', 'ㅋㅋㅋㅋ',
       'ㅋㅋㅋㅋㅋ', 'ㅎㅎ', 'ㅎㅎㅎ', 'ㅜㅜ', 'ㅠㅠ', 'ㅠㅠㅠ', 'ㅡㅡ', '가끔', '가는', '가볍게',
       '가서', '가슴', '가슴이', '가장', '가지고', '가진', '각본', '간만에', '갈수록', '감독',
       '감독님', '감독은', '감독의', '감독이', '감동', '감동과', '감동도', '감동을', '감동이',
       '감동적이고', '감동적인', '감사합니다', '갑자기', '강추', '같네요', '같다', '같습니다', '같아서',
       '같아요', '같은', '같은데', '같음', '같이', '개봉', '개뿔', '개연성', '개인적으로', '거의',
       '건지', '걸작', '겁나', '것도', '것은', '것을', '것이', '것이다', '게다가', '결국', '결말',
       '결말도', '결말은', '결말이', '계속', '공감이', '공포', '공포영화', '과연', '괜찮은', '괜히',
       '굉장히', '구성'], dtype=object)

### okt 이용해 동사, 명사 추출

In [16]:
!pip install konlpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 35.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.6/488.6 kB 39.4 MB/s eta 0:00:00


In [17]:
from konlpy.tag import Okt

In [18]:
tw_tag = Okt()

In [19]:
print('전체 형태소 추출 ', tw_tag.morphs(df.document[1]))
print('명사만 추출 ', tw_tag.nouns(df.document[1]))
print('태그 같이추출 ', tw_tag.pos(df.document[1]))

전체 형태소 추출  ['흠', '...', '포스터', '보고', '초딩', '영화', '줄', '....', '오버', '연기', '조차', '가볍지', '않구나']
명사만 추출  ['흠', '포스터', '보고', '초딩', '영화', '줄', '오버', '연기']
태그 같이추출  [('흠', 'Noun'), ('...', 'Punctuation'), ('포스터', 'Noun'), ('보고', 'Noun'), ('초딩', 'Noun'), ('영화', 'Noun'), ('줄', 'Noun'), ('....', 'Punctuation'), ('오버', 'Noun'), ('연기', 'Noun'), ('조차', 'Josa'), ('가볍지', 'Adjective'), ('않구나', 'Verb')]


### 함수를 만들어 전체 데이터셋을 모두 전처리 진행해야함

In [20]:
def my_tokenizer(doc):
    return[
        token
        for token, pos in tw_tag.pos(doc)
        if pos in ['Noun','Verb']
    ]

print('실제 결과 ', my_tokenizer(df.document[1]))

실제 결과  ['흠', '포스터', '보고', '초딩', '영화', '줄', '오버', '연기', '않구나']


In [21]:
re_cv = CountVectorizer(max_features=1000, tokenizer=my_tokenizer)

In [22]:
re_dtm = re_cv.fit_transform(df_docu)

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [23]:
for word, count in zip(re_cv.get_feature_names_out(), re_dtm[1].toarray()[0]):
    if count > 0:
        print(word, count, end=',')

보고 1,연기 1,영화 1,줄 1,초딩 1,포스터 1,흠 1,

### Cosine_Similarity 확인

In [24]:
from sklearn.metrics.pairwise import cosine_similarity

In [25]:
# 기준으로 볼 리뷰
st = len(df_docu[0])//2

In [26]:
source = df_docu[0][-st:]

In [27]:
df_docu[0]

'아 더빙.. 진짜 짜증나네요 목소리'

In [28]:
st

9

In [29]:
source

'짜증나네요 목소리'

In [30]:
# 코사인 유사도 게산하기 위해 벡터로 변환
source_rv=re_cv.transform([source])

In [31]:
source_rv

<1x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [32]:
sim_res = cosine_similarity(source_rv, re_dtm)

In [33]:
sim_res

array([[0.57735027, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [34]:
sim_res[0]

array([0.57735027, 0.        , 0.        , ..., 0.        , 0.        ,
       0.        ])

In [35]:
print('유사도 정렬', sorted(sim_res[0], reverse=True)[:100])

유사도 정렬 [1.0, 1.0, 0.8944271909999159, 0.8164965809277261, 0.7559289460184544, 0.7071067811865475, 0.7071067811865475, 0.7071067811865475, 0.7071067811865475, 0.7071067811865475, 0.7071067811865475, 0.7071067811865475, 0.7071067811865475, 0.7071067811865475, 0.7071067811865475, 0.7071067811865475, 0.7071067811865475, 0.7071067811865475, 0.7071067811865475, 0.6963106238227914, 0.5773502691896258, 0.5773502691896258, 0.5773502691896258, 0.5773502691896258, 0.5773502691896258, 0.5773502691896258, 0.5773502691896258, 0.5773502691896258, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.48507125007266594, 0.47140452079103173, 0.4472135954999579, 0.4472135954999579, 0.4472135954999579, 0.4472135954999579, 0.4472135954999579, 0.4472135954999579, 0.4472135954999579, 0.4082482904638631, 0.4082482904638631, 0.4082482904638631, 0.4082482904638631, 0.4082482904638631, 0.4082482904638631, 0.3779644730092272, 0.3779644730092272, 0.3779644730092272, 0.3779644730092272, 0.3779644730092

In [36]:
print('가장 유사한 리뷰는?', np.argmax(sim_res[0]))

가장 유사한 리뷰는? 7876


In [37]:
df_docu[7876]

'김용만의 목소리가 좋았다.'

In [38]:
print(sim_res[0].argsort()[3])

33311


In [39]:
df_docu[33311]

'정말 내인생 최고의 영화'

### 카운트 기반으로 할 때 문제
- 단어가 더 많다고 해서 꼭 중요한 건 아닐 수 있음

## TF-IDF (Term Frequency - Inverse Document Frequency)
- 단어빈도 - 역문서빈도
- 카운트 대신 단어의 빈도에 그 단어가 출연한 문서의 수의 역수를 곱하는 것
- == 단어의 빈도를 그 단어가 나타난 문서의 수로 나누는 것
- 더 의미있는 단어 추출 가능

In [40]:
from sklearn.feature_extraction.text import TfidfTransformer

In [41]:
transformer = TfidfTransformer()
transformer

TfidfTransformer()

In [42]:
rv_tfidf = transformer.fit_transform(re_dtm)

In [43]:
rv_tfidf

<50000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 227438 stored elements in Compressed Sparse Row format>

In [44]:
re_dtm[10].toarray()[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

tf_idf (빈도 기반), 카운팅이 아닌 확률처럼 소수로 표현

In [45]:
rv_tfidf[0].toarray()[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [46]:
source

'짜증나네요 목소리'

In [47]:
tf = TfidfTransformer()
rv_tfidf = tf.fit_transform(re_dtm)

In [48]:
source_idf = tf.transform(source_rv)

In [49]:
source_idf

<1x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [50]:
sim_res_tfidf = cosine_similarity(source_idf, rv_tfidf)

In [51]:
sim_res_tfidf[0]

array([0.67803893, 0.        , 0.        , ..., 0.        , 0.        ,
       0.        ])

In [52]:
print('가장 유사한 리뷰는?', np.argmax(sim_res_tfidf[0]))

가장 유사한 리뷰는? 7876


In [54]:
df_docu[7876]

'김용만의 목소리가 좋았다.'